name: Run the bot

on:
  schedule:
  - cron: '00 6 * * *' # Runs the bot daily at 6am UTC
  - cron: '30 19 * * *' # Runs at 7:30pm UTC
  # Add support for manual triggering
  workflow_dispatch:
  #  inputs:
  #    puzzleType:
  #      description: 'Puzzle Type'
  #      required: true
  #      default: 'RANDOM'
  #      type: choice
  #      options:
  #      - RANDOM
  #      - Anagram
  #      - Anagram7
  #      - PrimeFactors

jobs:
  run_bot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run the bot
      run: |
        python -m puzzlebot --access-token ${{ secrets.MASTODON_ACCESS_TOKEN }}
